package com.humanresourcesapp.entities.enums;

public enum EAccessIdentifier {
    EXPENDITURE_SAVE,
    EXPENDITURE_APPROVE,
    EXPENDITURE_DECLINE,
    EXPENDITURE_CANCEL,
    OFFER_SAVE,
    OFFER_APPROVE,
    OFFER_DECLINE,
    OFFER_CANCEL,
    CONTACT_US_SAVE,
    WELCOME,
    LEAVE_SAVE,
    LEAVE_APPROVE,
    LEAVE_DECLINE,
    LEAVE_CANCEL,
}
