server:
  port: 9090

spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 2000MB
#      max-request-size: 2150MB
#    cloud:
#      gcp:
#        config:
#          project-id: hip-field-428707-f0
#  main:
#    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: admin
      password: 1234
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HumanResourcesDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate.jdbc.time-zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: hevalcanaslan@gmail.com
    password: mfxv rqbt kqno puii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

aws:
  region: ${AWS_REGION}
  s3:
    buckets:
      customer: easyhumanres
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}



