server:
  port: 9090

spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HumanResourcesDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

