export enum ELeaveType {
    ANNUAL = "ANNUAL",
    HALF_ANNUAL = "HALF_ANNUAL",
    MATERNITY = "MATERNITY",
    PATERNITY = "PATERNITY",
    SICK = "SICK",
    BEREAVEMENT = "BEREAVEMENT",
    PERSONAL = "PERSONAL",
    FAMILY_CARE = "FAMILY_CARE",
    MILITARY = "MILITARY",
    MARRIAGE = "MARRIAGE",
    JURY_DUTY = "JURY_DUTY",
    UNPAID = "UNPAID",
    OTHER = "OTHER"
}