export enum EDefinitionType {
    LEAVE_TYPE = 'LEAVE_TYPE',
    SHIFT_TYPE = 'SHIFT_TYPE',
    JOB_TYPE = 'JOB_TYPE',
    EMPLOYEE_TYPE = 'EMPLOYEE_TYPE',
    POSITION = 'POSITION',
    DEPARTMENT = 'DEPARTMENT'
}