server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: humanresourceapp
          uri: http://34.118.237.3:9090/
          predicates:
            - Path=/dev/v1/**
        - id: humanresourceapp
          uri: http://34.118.237.3:9090/
          predicates:
            - Path=/uploads/**
        - id: humanresourceappreact
          uri: http://34.118.226.187:80 #hedef adres
          predicates:
            - Path=/**
